### ISSUE TITLE
Can "noarch: python" be used?

### ISSUE THREAD

**Issue by PhilipMay** [conda-forge/six-feedstock#14]
Hi, 
can this package be build with `noarch: python` option?
I think yes...

Also see here: https://conda-forge.org/docs/meta.html#building-noarch-packages

If you want me to I can provide a PR. 

Thanks,
Philip

**Comment by jakirkham** [comment]
This was tried before and was problematic. ( https://github.com/conda-forge/six-feedstock/pull/10 )

**Comment by PhilipMay** [comment]
What about the idea to write a comment to `meta.yaml` with a link to those issues to make it clear and avoid questions like this?
