### ISSUE TITLE
noarch leads to ImportError (on windoze)

### ISSUE THREAD

**Issue by marscher** [conda-forge/six-feedstock#9]
https://ci.appveyor.com/project/marscher/pyemma/build/1.0.3063/job/wrepwjo9ehgmiki2#L113

pinning to 1.10 avoids the problem, since these pkgs have been built with python arch dependency.
https://ci.appveyor.com/project/marscher/pyemma/build/job/8ajksepqxn2rpecg

Updating conda also drags in six, so one would have to reinstall six after conda update (I think the old conda-version on Appveyor is not capable of noarch pkgs)

**Comment by ocefpaf** [comment]
`six` probably does something under the hood that is not conda `noarch` safe. I'll rever that and pull the package. Thanks for the report.

**Comment by jakirkham** [comment]
Out of curiosity, what happens if you upgrade `conda` only first and then upgrade everything else?

**Comment by ocefpaf** [comment]
@jjhelmus I guess that until AppVeyor upgrades their `miniconda` it is better if we don't use `noarch` in the packages that will cause that `conda update` issue.

**Comment by jjhelmus** [comment]
Agreed. I've been avoiding `noarch: python` in packages that conda depends on in berryconda to avoid update issues as well as to facilitate the creation of installers using `constructor` which does not support noarch packages at this time.

**Comment by jakirkham** [comment]
Would add that it appears the Miniconda being used on AppVeyor is `C:\Miniconda3`, which is a 32-bit Python 3.4 based Miniconda. Discussed with AppVeyor about getting this one upgraded some time ago and basically they said they would only update it if a new Miniconda for Python 3.4 was released. As that is not going to happen, that Miniconda will stay old. Good new is there are [newer Minicondas available with newer Pythons]( https://www.appveyor.com/docs/build-environment/#miniconda ). Recommend switching over to one of these, @marscher.

**Comment by marscher** [comment]
On 09/21/2017 03:37 PM, jakirkham wrote:
> Out of curiosity, what happens if you upgrade |conda| only first and
> then upgrade everything else?
I've tried that, without success.

**Comment by marscher** [comment]
On 09/21/2017 04:22 PM, jakirkham wrote:
> Would add that it appears the Miniconda being used on AppVeyor is
> |C:\Miniconda3|, which is a 32-bit Python 3.4 based Miniconda. Discussed
> with AppVeyor about getting this one upgraded some time ago and
> basically they said they would only update it if a new Miniconda for
> Python 3.4 was released. As that is not going to happen, that Miniconda
> will stay old. Good new is there are newer Minicondas available with
> newer Pythons
> <https://www.appveyor.com/docs/build-environment/#miniconda>. Recommend
> switching over to one of these, @marscher <https://github.com/marscher>.
Thank you so much for this advice, will do that soon.

**Comment by jakirkham** [comment]
> Agreed. I've been avoiding `noarch: python` in packages that conda depends on in berryconda to avoid update issues as well as to facilitate the creation of installers using `constructor` which does not support noarch packages at this time.

Interesting. Was not aware of that. For reference, issue ( https://github.com/conda/constructor/issues/86 ) is requesting `noarch: python` support.
